name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - "1.20.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: danieljimeneznz/ensure-files-changed@v4.1.0
        with:
          require-changes-to: |
            CHANGELOG.md
          prevent-changes-to: |
            LICENSE.md
          token: ${{ secrets.GITHUB_TOKEN }}